### ISSUE TITLE
ObjectDetectionCoral cannot start , has Numpy error

### ISSUE THREAD

**Issue by ingus16** [codeproject/CodeProject.AI-Server#118]
**Area of Concern**
- [ ] Server module wont start ObjectDetectionCoral
**Describe the bug**

I have USB-C version of  Coral TPU
Tried to install coral module in the Code project AI , received error as per screenshot.
Tried on the docker environment , has same issue.
When start module then this error appears.

**Expected behavior**
Installed and can be started without errors

**Screenshots**
![image](https://github.com/codeproject/CodeProject.AI-Server/assets/37122419/4b5d2067-4820-477d-9fcc-0ffe12e8fcb5)

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.6.5
 - OS: Windows
 - System 16Gb
 - GPU Intel Iris 530
 - GPU RAM 1GB

**Comment by beginnersguide** [comment]
**Area of Concern**
 
* [ X ]  Server module:  Object Detection (Coral) 2.3.1

**Describe the bug**
 

```
08:06:56:ObjectDetectionCoral: A module that was compiled using NumPy 1.x cannot be run in
08:06:56:ObjectDetectionCoral: NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
08:06:56:ObjectDetectionCoral: versions of NumPy, modules must be compiled with NumPy 2.0.
08:06:56:ObjectDetectionCoral: Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
08:06:56:ObjectDetectionCoral: If you are a user of the module, the easiest solution will be to
08:06:56:ObjectDetectionCoral: downgrade to 'numpy<2' or try to upgrade the affected module.
08:06:56:ObjectDetectionCoral: We expect that some modules will need time to support NumPy 2.
08:06:56:ObjectDetectionCoral: Traceback (most recent call last):  File "/app/modules/ObjectDetectionCoral/objectdetection_coral_adapter.py", line 229, in 
08:06:56:ObjectDetectionCoral:     CoralObjectDetector_adapter().start_loop()
08:06:56:ObjectDetectionCoral:   File "/app/modules/ObjectDetectionCoral/bin/linux/python39/venv/lib/python3.9/site-packages/codeproject_ai_sdk/module_runner.py", line 278, in start_loop
08:06:56:ObjectDetectionCoral:     self.initialise()
08:06:56:ObjectDetectionCoral:   File "/app/modules/ObjectDetectionCoral/objectdetection_coral_adapter.py", line 54, in initialise
08:06:56:ObjectDetectionCoral:     import objectdetection_coral_multitpu as odcm
08:06:56:ObjectDetectionCoral:   File "/app/modules/ObjectDetectionCoral/objectdetection_coral_multitpu.py", line 51, in 
08:06:56:ObjectDetectionCoral:     from tpu_runner import TPURunner, INTERPRETER_LIFESPAN_SECONDS
08:06:56:ObjectDetectionCoral:   File "/app/modules/ObjectDetectionCoral/tpu_runner.py", line 33, in 
08:06:56:ObjectDetectionCoral:     from pycoral.utils import edgetpu
08:06:56:ObjectDetectionCoral:   File "/app/modules/ObjectDetectionCoral/bin/linux/python39/venv/lib/python3.9/site-packages/pycoral/utils/edgetpu.py", line 24, in 
08:06:56:ObjectDetectionCoral:     from pycoral.pybind._pywrap_coral import GetRuntimeVersion as get_runtime_version
08:06:56:ObjectDetectionCoral: AttributeError: _ARRAY_API not found
08:06:56:ObjectDetectionCoral: Traceback (most recent call last):
08:06:56:ObjectDetectionCoral:   File "/app/modules/ObjectDetectionCoral/objectdetection_coral_adapter.py", line 229, in 
08:06:56:ObjectDetectionCoral:     CoralObjectDetector_adapter().start_loop()
08:06:56:ObjectDetectionCoral:   File "/app/modules/ObjectDetectionCoral/bin/linux/python39/venv/lib/python3.9/site-packages/codeproject_ai_sdk/module_runner.py", line 278, in start_loop
08:06:56:ObjectDetectionCoral:     self.initialise()
08:06:56:ObjectDetectionCoral:   File "/app/modules/ObjectDetectionCoral/objectdetection_coral_adapter.py", line 54, in initialise
08:06:56:ObjectDetectionCoral:     import objectdetection_coral_multitpu as odcm
08:06:56:ObjectDetectionCoral:   File "/app/modules/ObjectDetectionCoral/objectdetection_coral_multitpu.py", line 51, in 
08:06:56:ObjectDetectionCoral:     from tpu_runner import TPURunner, INTERPRETER_LIFESPAN_SECONDS
08:06:56:ObjectDetectionCoral:   File "/app/modules/ObjectDetectionCoral/tpu_runner.py", line 33, in 
08:06:56:ObjectDetectionCoral:     from pycoral.utils import edgetpu
08:06:56:ObjectDetectionCoral:   File "/app/modules/ObjectDetectionCoral/bin/linux/python39/venv/lib/python3.9/site-packages/pycoral/utils/edgetpu.py", line 24, in 
08:06:56:ObjectDetectionCoral:     from pycoral.pybind._pywrap_coral import GetRuntimeVersion as get_runtime_version
08:06:56:ObjectDetectionCoral: SystemError: initialization of _pywrap_coral raised unreported exception
08:06:56:ObjectDetectionCoral: Self test: Self-test failed
08:06:56:ObjectDetectionCoral: Module setup time 00:01:10
08:06:56:ObjectDetectionCoral:                 Setup complete                                        
08:06:56:ObjectDetectionCoral: Total setup time 00:01:13
```


**Your System (please complete the following information):**
 
* CodeProject.AI Server version: 2.6.5
* OS: Ubuntu 22.04.3 LTS
* RAM: 8GB
* GPU: Intel(R) Core(TM) i3-9100T CPU @ 3.10GHz
* GPU: Onboard Intel UHD Graphics 630
* Google Coral TPU USB-Accelarator

**Comment by ingus16** [comment]
Can be closed from my side.
Now works

**Comment by ChrisMaunder** [comment]
Fixed
