### ISSUE TITLE
Lience Plate Reader - Failed to start - CPAI 2.6.5

### ISSUE THREAD

**Issue by Fire-Rage** [codeproject/CodeProject.AI-Server#119]
**Area of Concern**
CPAI - 2.6.5
License Plate Reader 3.1.0  - Failed to start
running on windows 11
System:           Windows
Operating System: Windows (Microsoft Windows 11 version 10.0.22631)
CPU- Intel i5-10400 CPU @ 2.90GHz (Intel)
GPU (Primary):  NVIDIA GeForce GTX 1650 (4 GiB) (NVIDIA) 
                  Driver: 522.06, CUDA: 11.8 - cuDNN: 9.0
RAM - 32gb
.NET framework:   .NET 7.0.20

**Describe the bug**
My system was working flawlessly. then I upgraded from 2.6.2 to 2.6.5 and it broke the LPR module. 
This is an error that stands out 
19:40:01:ALPR_adapter.py: RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
I tried this on a docker container on unraid, and tried on Windows 10 also. All have the same issue
I downgraded to 2.6.2 and still had the same issue. Seems to be the new version of the module causing the issue. 
I also noticed it says CPU, As it was working with GPU before. But with this failing to start is the main issue. guessing something has to dod with numpy. I see in the logs of the LPR module in 3.2.1 they corrected numpy 2.0 issue but for some reason it will only let me install 3.1.0 of the LPR

LOGS
---
Started License Plate Reader module
19:40:01:ALPR_adapter.py: RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
19:40:01:ALPR_adapter.py: Traceback (most recent call last):
19:40:01:ALPR_adapter.py:   File "C:\Program Files\CodeProject\AI\modules\ALPR\ALPR_adapter.py", line 16, in 
19:40:01:ALPR_adapter.py:     from ALPR import init_detect_platenumber, detect_platenumber
19:40:01:ALPR_adapter.py:   File "C:\Program Files\CodeProject\AI\modules\ALPR\ALPR.py", line 7, in 
19:40:01:ALPR_adapter.py:     import utils.tools as tool
19:40:01:ALPR_adapter.py:   File "C:\Program Files\CodeProject\AI\modules\ALPR\utils\tools.py", line 2, in 
19:40:01:ALPR_adapter.py:     import cv2
19:40:01:ALPR_adapter.py:   File "C:\Program Files\CodeProject\AI\modules\ALPR\bin\windows\python39\venv\lib\site-packages\cv2\__init__.py", line 181, in 
19:40:01:ALPR_adapter.py:     bootstrap()
19:40:01:ALPR_adapter.py:   File "C:\Program Files\CodeProject\AI\modules\ALPR\bin\windows\python39\venv\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
19:40:01:ALPR_adapter.py:     native_module = importlib.import_module("cv2")
19:40:01:ALPR_adapter.py:   File "C:\Program Files\CodeProject\AI\runtimes\bin\windows\python39\lib\importlib\__init__.py", line 127, in import_module
19:40:01:ALPR_adapter.py:     return _bootstrap._gcd_import(name[level:], package, level)
19:40:01:ALPR_adapter.py: ImportError: numpy.core.multiarray failed to import
19:40:01:Module ALPR has shutdown
19:40:01:ALPR_adapter.py: has exited
![image](https://github.com/codeproject/CodeProject.AI-Server/assets/16928907/1d184c12-4051-4e08-9403-6f05d3dee22d)

**Comment by Fire-Rage** [comment]
![image](https://github.com/codeproject/CodeProject.AI-Server/assets/16928907/34e1bbe2-4f7d-4e22-a725-89edc9c0d99c)

Just updated the module to 3.2.2 as it now allowed me to. 
still failing to start but this is what i get now.
when i install it now it also says this. 
![image](https://github.com/codeproject/CodeProject.AI-Server/assets/16928907/03c6b14f-de61-4b20-94b9-daa60fe20863)

**Comment by xavan83** [comment]
See [https://github.com/codeproject/CodeProject.AI-Server/issues/87](url)
