### ISSUE TITLE
License Plate Reader Install Failures

### ISSUE THREAD

**Issue by SquigglyPiffin** [codeproject/CodeProject.AI-Server#160]
Hey, I am trying to install the license plate reader. I can install it, but every time I do, there is a failure that causes the module to shutdown. I had been able to resolve it once before after days of trying, but I made a backup and reinstalled the module from that (previously working) backup and now it is failing again. Reinstalling brand new causes the same issue too. I have attached the entire install log as a txt file. Please help me, I am struggling with this. All my other modules work perfectly (Facial recognition, coral and yolov8 object detection)

**Here are the failures I get:**

08:26:12:ALPR: - Installing PaddlePaddle, Parallel Distributed Deep Learning...Looking in indexes: https://mirror.baidu.com/pypi/simple
08:26:14:ALPR: WARNING: Skipping page https://mirror.baidu.com/pypi/simple/paddlepaddle-gpu/ because the GET request got Content-Type: application/octet-stream. The only supported Content-Types are application/vnd.pypi.simple.v1+json, application/vnd.pypi.simple.v1+html, and text/html
08:26:14:ALPR: ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==2.6.0 (from versions: none)
08:26:14:ALPR: ERROR: No matching distribution found for paddlepaddle-gpu==2.6.0
08:26:15:ALPR: (❌ failed check) done

08:27:40:ALPR: Traceback (most recent call last):
08:27:40:ALPR:   File "C:\Program Files\CodeProject\AI\modules\ALPR\ALPR_adapter.py", line 11, in 
08:27:40:ALPR:     from ALPR import init_detect_platenumber, detect_platenumber
08:27:40:ALPR:   File "C:\Program Files\CodeProject\AI\modules\ALPR\ALPR.py", line 17, in 
08:27:40:ALPR:     from paddleocr import PaddleOCR
08:27:40:ALPR:   File "C:\Program Files\CodeProject\AI\modules\ALPR\bin\windows\python39\venv\lib\site-packages\paddleocr\__init__.py", line 14, in 
08:27:40:ALPR:     from .paddleocr import *
08:27:40:ALPR:   File "C:\Program Files\CodeProject\AI\modules\ALPR\bin\windows\python39\venv\lib\site-packages\paddleocr\paddleocr.py", line 21, in 
08:27:40:ALPR:     import paddle
08:27:40:ALPR: ModuleNotFoundError: No module named 'paddle'

08:25:49:ALPR: 'winget' is not recognized as an internal or external command,
08:25:49:ALPR: operable program or batch file.

[ALPR Log.txt](https://github.com/user-attachments/files/17750395/ALPR.Log.txt)

**Comment by SquigglyPiffin** [comment]
Okay, I fixed it. For future reference below. This is specific for Python 3.9
In Powershell as Admin run these:

cd "PathTo\CodeProject\AI\modules\ALPR\bin\windows\python39\venv\Scripts"

.\activate

pip install paddlepaddle-gpu==2.6.0 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/cuda11.8.html
