### ISSUE TITLE
CodeProject.AI v2.9.4 failed to install Object Detection (YOLOv5 .NET) 1.13.0

### ISSUE THREAD

**Issue by MikeLud** [codeproject/CodeProject.AI-Server#199]
**Area of Concern**
- [ ] Server
- [X] Behaviour of one or more Modules [Object Detection (YOLOv5 .NET) 1.13.0]
- [X] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
CodeProject.AI v2.9.4 failed to install Object Detection (YOLOv5 .NET) 1.13.0.

**Expected behavior**
CodeProject.AI v2.9.4 to install Object Detection (YOLOv5 .NET) 1.13.0.

**Screenshots**
![image](https://github.com/user-attachments/assets/92ac8bc7-39eb-4e04-8e61-e852016f59f2)

**Your System (please complete the following information):**
```
Server version:   2.9.4
System:           Windows
Operating System: Windows (Windows 10 Redstone)
CPUs:             AMD Ryzen 9 5950X 16-Core Processor             (AMD)
                  1 CPU x 16 cores. 32 logical processors (x64)
GPU (Primary):    NVIDIA GeForce RTX 4090 (24 GiB) (NVIDIA) 
                  Driver: 566.14, CUDA: 12.4.99 (up to: 12.7), Compute: 8.9, cuDNN: 8.9
System RAM:       128 GiB
Platform:         Windows
BuildConfig:      Release
Execution Env:    Native
Runtime Env:      Production
Runtimes installed:
  .NET runtime:     9.0.0
  .NET SDK:         8.0.404
  Default Python:   3.11.0
  Go:               Not found
  NodeJS:           20.8.1
  Rust:             Not found
Video adapter info:
  NVIDIA GeForce RTX 4090:
    Driver Version     32.0.15.6614
    Video Processor    NVIDIA GeForce RTX 4090
System GPU info:
  GPU 3D Usage       3%
  GPU RAM Usage      4.1 GiB
Global Environment variables:
  CPAI_APPROOTPATH = <root>
  CPAI_PORT        = 32168
```

**Additional context**
Install Log

```
2024-12-01 16:57:35:              Installing CodeProject.AI Analysis Module                
2024-12-01 16:57:35: ======================================================================
2024-12-01 16:57:35:                    CodeProject.AI Installer                           
2024-12-01 16:57:35: ======================================================================
2024-12-01 16:57:36: 754.6Gb of 1907Gb available on (No label) (Windows 10 x86_64 - windows)
2024-12-01 16:57:36: General CodeProject.AI setup                                          
2024-12-01 16:57:36: Checking for VC++ Redist...v14 Present.
2024-12-01 16:57:36: Creating Directories...done
2024-12-01 16:57:36: GPU support                                                           
2024-12-01 16:57:37: CUDA Present...Yes (CUDA 12.4, cuDNN 8.9, CUDA Toolkit: true)
2024-12-01 16:57:37: Updating path to include cuDNN
2024-12-01 16:57:38: ROCm Present...No
2024-12-01 16:57:38: Checking for .NET 9.0...Checking runtimes...All good. Found .NET aspnetcore 9
2024-12-01 16:57:41: Reading ObjectDetectionYOLOv5Net settings.......done
2024-12-01 16:57:41: Installing module Object Detection (YOLOv5 .NET) 1.13.0               
2024-12-01 16:57:41: Internal module install
2024-12-01 16:57:47: onnxruntime.dll: ZIP decompression failed (-3)
2024-12-01 16:57:47: tar: Error exit delayed from previous errors.
2024-12-01 16:57:56: New-Object : Exception calling ".ctor" with "3" argument(s): "End of Central Directory record could not be found."
2024-12-01 16:57:56: At 
2024-12-01 16:57:56: C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:934 
2024-12-01 16:57:56: char:23
2024-12-01 16:57:56: + ... ipArchive = New-Object -TypeName System.IO.Compression.ZipArchive -Ar ...
2024-12-01 16:57:56: +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-12-01 16:57:56:     + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
2024-12-01 16:57:56:     + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
2024-12-01 16:57:56: Downloading ObjectDetectionYOLOv5Net-DirectML-1.13.0.zip...Expanding...Tar failed - moving to PowerShell...done.
2024-12-01 16:57:56: Copying contents of ObjectDetectionYOLOv5Net-DirectML-1.13.0.zip to bin...done
2024-12-01 16:58:02: Downloading YOLO ONNX models...Expanding...done.
2024-12-01 16:58:03: Copying contents of yolonet-models.zip to assets...done
2024-12-01 16:58:06: Downloading Custom YOLO ONNX models...Expanding...done.
2024-12-01 16:58:06: Copying contents of yolonet-custom-models.zip to custom-models...done
2024-12-01 16:58:06: Scanning modulesettings for downloadable models...No models specified
2024-12-01 16:58:06: Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.EventLog, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
2024-12-01 16:58:06: File name: 'System.Diagnostics.EventLog, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
2024-12-01 16:58:06:    at Microsoft.Extensions.Logging.EventLog.EventLogLogger..ctor(String name, EventLogSettings settings, IExternalScopeProvider externalScopeProvider)
2024-12-01 16:58:06:    at Microsoft.Extensions.Logging.EventLog.EventLogLoggerProvider.CreateLogger(String name)
2024-12-01 16:58:06:    at Microsoft.Extensions.Logging.LoggerInformation..ctor(ILoggerProvider provider, String category)
2024-12-01 16:58:06:    at Microsoft.Extensions.Logging.LoggerFactory.CreateLoggers(String categoryName)
2024-12-01 16:58:06:    at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
2024-12-01 16:58:06:    at Microsoft.Extensions.Logging.Logger`1..ctor(ILoggerFactory factory)
2024-12-01 16:58:06:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
2024-12-01 16:58:06:    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
2024-12-01 16:58:06:    at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2024-12-01 16:58:06:    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
2024-12-01 16:58:06:    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2024-12-01 16:58:06:    at Microsoft.Extensions.Hosting.HostBuilder.<>c__DisplayClass35_0.<PopulateServiceCollection>b__2(IServiceProvider _)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
2024-12-01 16:58:06:    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2024-12-01 16:58:06:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2024-12-01 16:58:06:    at Microsoft.Extensions.Hosting.HostBuilder.ResolveHost(IServiceProvider serviceProvider, DiagnosticListener diagnosticListener)
2024-12-01 16:58:06:    at Microsoft.Extensions.Hosting.HostBuilder.Build()
2024-12-01 16:58:06:    at CodeProject.AI.Modules.ObjectDetection.YOLOv5.Program.Main(String[] args)
2024-12-01 16:58:06:    at CodeProject.AI.Modules.ObjectDetection.YOLOv5.Program.<Main>(String[] args)
2024-12-01 16:58:11: Self test: Self-test passed
2024-12-01 16:58:11: Module setup time 00:00:32.30
2024-12-01 16:58:11: Setup complete                                                        
2024-12-01 16:58:11: Total setup time 00:00:35.53
```

**Comment by MikeLud** [comment]
@ChrisMaunder it looks like `ObjectDetectionYOLOv5Net-DirectML-1.13.0.zip` is corrupt.

**Comment by ChrisMaunder** [comment]
I've rebuilt and re-uploaded.

**Comment by MikeLud** [comment]
@ChrisMaunder It still looks to be corrupt.

![image](https://github.com/user-attachments/assets/a6969030-5d10-4980-b5c0-44c52b60d7bd)

**Comment by MikeLud** [comment]
@ChrisMaunder I was able to download a good version of the file from
https://codeproject-ai-bunny.b-cdn.net/server/assets/binaries/ObjectDetectionYOLOv5Net-DirectML-1.13.0.zip

**Comment by ChrisMaunder** [comment]
I was just about to suggest that. Did you disable caching in the dashboard? (I assume you did because I know you're careful about that stuff). Might be caching from our new hosting provider or an over-zealous browser

**Comment by MikeLud** [comment]
@ChrisMaunder I did disable caching. I replaced the cached file with the one I manual downloaded and reinstalled with caching and I get this.

```
3:38:52:ObjectDetectionYOLOv5Net: Downloading ObjectDetectionYOLOv5Net-DirectML-1.13.0.zip from https://codeproject-ai-bunny.b-cdn.net/server/assets/binaries/ to C:\Program Files\CodeProject\AI\downloads\modules\assets\ObjectDetectionYOLOv5Net
23:38:52:ObjectDetectionYOLOv5Net: Downloading ObjectDetectionYOLOv5Net-DirectML-1.13.0.zip...Checking...
23:38:52:ObjectDetectionYOLOv5Net: already exists...Expanding...Heading to C:\Program Files\CodeProject\AI\downloads\modules\assets\ObjectDetectionYOLOv5Net
23:38:52:ObjectDetectionYOLOv5Net: Extracting ObjectDetectionYOLOv5Net-DirectML-1.13.0.zip
23:38:52:ObjectDetectionYOLOv5Net: CodeProject.AI.Module.SDK.dll: ZIP compressed data is wrong size (read 62419, expected 62424)
23:38:52:ObjectDetectionYOLOv5Net: tar: Damaged Zip archive
23:38:52:ObjectDetectionYOLOv5Net: tar: Error exit delayed from previous errors.
23:38:53:ObjectDetectionYOLOv5Net: Exception calling "ExtractToFile" with "3" argument(s): "A local file header is corrupt."
23:38:53:ObjectDetectionYOLOv5Net: At 
23:38:53:ObjectDetectionYOLOv5Net: C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:1056 
23:38:53:ObjectDetectionYOLOv5Net: char:25
23:38:53:ObjectDetectionYOLOv5Net: + ...             [System.IO.Compression.ZipFileExtensions]::ExtractToFile( ...
23:38:53:ObjectDetectionYOLOv5Net: +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
23:38:53:ObjectDetectionYOLOv5Net:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
23:38:53:ObjectDetectionYOLOv5Net:     + FullyQualifiedErrorId : InvalidDataException
23:38:53:ObjectDetectionYOLOv5Net: Tar failed - moving to PowerShell...done.
23:38:53:ObjectDetectionYOLOv5Net: Copying contents of ObjectDetectionYOLOv5Net-DirectML-1.13.0.zip to bin...done
```
