### ISSUE TITLE
Face processing fails to start

### ISSUE THREAD

**Issue by drcmputr** [codeproject/CodeProject.AI-Server#214]
**Area of Concern**
- [ ] Server
- [X] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
Face processing fails to start.  I get the following error in the logs:

08:35:49:Started Face Processing module
08:35:50:face.py: Using PIL for image manipulation (Either OpenCV or numpy not available for this module)
08:35:50:face.py: GPU in use: NVIDIA GeForce RTX 4090
08:35:50:face.py: Traceback (most recent call last):
08:35:50:face.py:   File "C:\Program Files\CodeProject\AI\modules\FaceProcessing\intelligencelayer\face.py", line 37, in 
08:35:50:face.py:     from process import YOLODetector
08:35:50:face.py:   File "C:\Program Files\CodeProject\AI\modules\FaceProcessing\intelligencelayer\.\process.py", line 2, in 
08:35:50:face.py:     import cv2
08:35:50:face.py: ModuleNotFoundError: No module named 'cv2'
08:35:51:Module FaceProcessing has shutdown

**Your System (please complete the following information):**
 - CodeProject.AI Server version: 2.9.4
 - OS: Windows 11
 - System RAM 64GB
 - GPU (if available) GeForce RTX 4090
 - GPU RAM (if available)  24GB

**Additional context**
I only have Object Detection (YOLOv8) and Face Processing installed.  Does the Face Processing module need something else installed to work?

**Comment by ChrisMaunder** [comment]
Pleased try uninstalling then reinstalling the Face module via the dashboard.

**Comment by drcmputr** [comment]
I just tried that (again) and I have the same issue.  It shows as started, then a minute or two later says "failed to start" with the same errors in the logs.

12:53:10:Started Face Processing module
12:53:10:Installer exited with code 1
12:53:12:face.py: Using PIL for image manipulation (Either OpenCV or numpy not available for this module)
12:53:12:face.py: GPU in use: NVIDIA GeForce RTX 4090
12:53:12:face.py: Traceback (most recent call last):
12:53:12:face.py:   File "C:\Program Files\CodeProject\AI\modules\FaceProcessing\intelligencelayer\face.py", line 37, in 
12:53:12:face.py:     from process import YOLODetector
12:53:12:face.py:   File "C:\Program Files\CodeProject\AI\modules\FaceProcessing\intelligencelayer\.\process.py", line 2, in 
12:53:12:face.py:     import cv2
12:53:12:face.py: ModuleNotFoundError: No module named 'cv2'
12:53:12:Module FaceProcessing has shutdown
12:53:12:face.py: has exited
12:53:13:Module FaceProcessing started successfully.

**Comment by drcmputr** [comment]
![image](https://github.com/user-attachments/assets/4521da6a-c3b7-4391-a791-6c5c78a7ca95)

**Comment by ChrisMaunder** [comment]
@drcmputr Please click that 'info' button on the RHS of the Face listing, then scroll down till you see the install log. Can you please cut and paste that here?

**Comment by drcmputr** [comment]
When I click on Info, all it shows is this.  I don't see any install log.

Module 'Face Processing' 1.12.2 (ID: FaceProcessing)
Valid:            True
Module Path:      <root>\modules\FaceProcessing
Module Location:  Internal
AutoStart:        True
Queue:            faceprocessing_queue
Runtime:          python3.7
Runtime Location: Shared
FilePath:         intelligencelayer\face.py
Start pause:      3 sec
Parallelism:      0
LogVerbosity:     
Platforms:        all,!jetson
GPU Libraries:    installed if available
GPU:              use if supported
Accelerator:      
Half Precision:   enable
Environment Variables
   APPDIR             = <root>\modules\FaceProcessing\intelligencelayer
   DATA_DIR           = C:\ProgramData\CodeProject\AI
   MODE               = MEDIUM
   MODELS_DIR         = <root>\modules\FaceProcessing\assets
   PROFILE            = desktop_gpu
   USE_CUDA           = True
   YOLOv5_AUTOINSTALL = false
   YOLOv5_VERBOSE     = false
Status Data:  
Started:      05 Dec 2024 12:53:10 PM Pacific Standard Time
LastSeen:     Not seen
Status:       Started
Requests:     0 (includes status calls)

![image](https://github.com/user-attachments/assets/46ed29f5-ba55-4fc9-ad91-6cc81b220244)

**Comment by ChrisMaunder** [comment]
Unfortunately the screenshot has cut the bottom off. See in the 'Info' popup the icon at the top right? Click that and it will copy the info window to the clipboard. Please paste just the text here.
