### ISSUE TITLE
Can't run Object Detection (YOLOv5 RKNN) 1.8.1 on latest

### ISSUE THREAD

**Issue by grinco** [codeproject/CodeProject.AI-Server#223]
Tried on 2.9.4 and 2.9.5, both upgrade from 2.9.2 and clean install. Keep getting the same result:
```
Infor Started Object Detection (YOLOv5 RKNN) module
Error objectdetection_fd_rknn_adapter.py: Traceback (most recent call last):
Error objectdetection_fd_rknn_adapter.py:   File "/app/modules/ObjectDetectionYoloRKNN/objectdetection_fd_rknn_adapter.py", line 14, in <module>
Error objectdetection_fd_rknn_adapter.py:     from objectdetection_fd_rknn import init_detect, do_detect
Error objectdetection_fd_rknn_adapter.py:   File "/app/modules/ObjectDetectionYoloRKNN/objectdetection_fd_rknn.py", line 26, in <module>
Error objectdetection_fd_rknn_adapter.py:     from module_logging import LogMethod
Error objectdetection_fd_rknn_adapter.py: ModuleNotFoundError: No module named 'module_logging'
Infor ** Module ObjectDetectionYoloRKNN has shutdown
Infor objectdetection_fd_rknn_adapter.py: has exited
```
If anyone knows a fix - a tip would be appreciated.

**Comment by grinco** [comment]
Looks like it's a module issue. Closing in favor of https://github.com/codeproject/CodeProject.AI-ObjectDetectionYoloRKNN/issues/2
