### ISSUE TITLE
Python Runtime Errors in Server Log: Tensor Size

### ISSUE THREAD

**Issue by dannyeverest** [codeproject/CodeProject.AI-Server#242]
New To Github, Thanks for getting me here CPAi. It's a bit of a headache but I am geeking out and loving it!
**Area of Concern**
- [!] Server
- [!] Python Runtime 3.8?

**Server Info**

This is how my CPai is hosted

Dellpoweregde r630>proxmox>windows10 pro vm> wsl2 debian>docker

Server version:   2.9.5
System:           Docker (Ubuntu 22.04.3 LTS)
Operating System: Linux (Ubuntu 22.04 Jammy Jellyfish)
CPUs:             Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (Intel)
                  1 CPU x 12 cores. 12 logical processors (x64)
GPU (Primary):    Quadro P2000 (5 GiB) (NVIDIA) 
                  Driver: 561.17, CUDA: 12.6 (up to: 12.6), Compute: 6.1, cuDNN: 8.9.6
System RAM:       29 GiB
Platform:         Linux
BuildConfig:      Release
Execution Env:    Docker
Runtime Env:      Production
Runtimes installed:
  .NET runtime:     9.0.0
  .NET SDK:         Not found
  Default Python:   3.10.12
  Go:               Not found
  NodeJS:           Not found
  Rust:             Not found
Video adapter info:
System GPU info:
  GPU 3D Usage       39%
  GPU RAM Usage      1,011 MiB
Global Environment variables:
  CPAI_APPROOTPATH = <root>
  CPAI_PORT        = 32168

**Describe the bug**
 Blue Iris, using ai as trigger, works reliably on up to 2 cameras. anything more and it eventually spits out this in the server logs:
 
 20:52:56:Response rec'd from Object Detection (YOLOv5 6.2) command 'detect' (...00c13b) ['No objects found']  took 56ms
20:52:57:Response rec'd from Object Detection (YOLOv5 6.2) command 'detect' (...e80819) ['No objects found']  took 115ms
20:52:57:Object Detection (YOLOv5 6.2):  [RuntimeError] : Traceback (most recent call last):
  File "/app/preinstalled-modules/ObjectDetectionYOLOv5-6.2/detect.py", line 140, in do_detection
    det                  = detector(img, size=640)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yolov5/models/common.py", line 705, in forward
    y = self.model(x, augment=augment)  # forward
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yolov5/models/common.py", line 515, in forward
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yolov5/models/yolo.py", line 209, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/usr/local/lib/python3.8/dist-packages/yolov5/models/yolo.py", line 121, in _forward_once
    x = m(x)  # run
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yolov5/models/yolo.py", line 75, in forward
    wh = (wh * 2) ** 2 * self.anchor_grid[i]  # wh
RuntimeError: The size of tensor a (12) must match the size of tensor b (15) at non-singleton dimension 2
20:52:57:Response rec'd from Object Detection (YOLOv5 6.2) command 'detect' (...d674d8)
20:52:57:Response rec'd from Object Detection (YOLOv5 6.2) command 'detect' (...8e9b0a) ['Found car, car, car']  took 64ms
20:52:57:Response rec'd from Object Detection (YOLOv5 6.2) command 'detect' (...4d3cc4) ['Found car, car']  took 63ms
20:52:57:Response rec'd from Object Detection (YOLOv5 6.2) command 'detect' (...880dd4) ['No objects found']  took 48ms
20:52:58:Response rec'd from Object Detection (YOLOv5 6.2) command 'detect' (...4effb9) ['No objects found']  took 43ms
20:52:58:Response rec'd from Object Detection (YOLOv5 6.2) command 'detect' (...d8288a) ['Found car, car, car']  took 62ms

ADDITIONALLY when I open CPAI webgui the clock times on when requests comes in sag to up to ten minutes behind, then catches up a little later (30ish sec). This happens even with consistent low processing times. Not sure if that is only a gui thing to save memory, or if the server is getting behind. Processing times are usually low when I see this(40-70ms range).

**Expected behavior**
CPAI to be stable and not delay or error

**Screenshots**

**Additional context**
My cpu never maxes out, gpu hasn't gone over 39%.

At one point I was using motion to trigger, then sending 40 images with 750ms between each and it worked very reliable on one or 2 cameras. I bought the upgrade package for blueiris thinking it would help. Used the the ai as trigger feature, worked amazing on one or 2 cameras like my wild 40 image analysis. but as soon as i add more cameras it becomes unreliable.

I am going to give my windows vm system more memory  and 12 more cores as well as pin them to the socket in proxmox to prevent memory lag... but I dont think it will have any impact on this issue. 

I experimented with making another docker container on the same system to mesh together (1 instance of cpai doesn't have that much effect on my system performance, so I thought this would give me redundancy and access to more gpu/cpu resources, but i still got the same error in both a few min into pushing it past 2 cameras. )

It seems that these errors are related to python... would updating to a newer python work? am I on an outdated version or is 3,8 the normal for cpai?

 Why does my cpai server info say 3.10.12 and my runtime error reference 3.8?

**Comment by dannyeverest** [comment]
I looked up tensor size and learned it is related to the size of the image the ai is analyzing. I also tried forcing my camera resolutions to nothing past 640... didn't help. not sure it evens works like that, but i do not know what else to do.

**Comment by dannyeverest** [comment]
For anyone in the future: I disabled Yolov6.2 and installed yolov8 from the install modules tab and have done 10,000 without error. Still confused about what happen.

Not sure if the issue is gone, as when I started using docker and cpai with yolov6.2 it was looking pretty good at first aswell. 

I'll keep this thread updated, but if anyone has any ideas why it wouldn't work out of the box, I'm curious. I am planning on training my own models so I'm sure I'll do my fair share of debugging and troubleshooting.
