### ISSUE TITLE
python37 folder is empty/missing after installing v2.2.4

### ISSUE THREAD

**Issue by ahaverty** [codeproject/CodeProject.AI-Server#69]
**Area of Concern**
- [x] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [x] Installer
- [x] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
After installing v2.2.4, Object and Face detection fails to start, and the server logs complain about python37 missing.
(The folder `C:\Program Files\CodeProject\AI\runtimes\bin\windows\python37` is indeed empty when I look in file explorer)

**Your System (please complete the following information):**
 - CodeProject.AI Server version: v2.2.4
 - OS: Windows 10 Pro
 - System RAM: 16Gb
 - GPU: GeForce GTX 1060
 - GPU RAM: 6Gb

**Additional context**

```txt
2023-09-28 21:45:10: ** Operating System: Windows (Microsoft Windows 10.0.19045)
2023-09-28 21:45:10: ** CPUs:             Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (Intel)
2023-09-28 21:45:10: **                   1 CPU x 4 cores. 8 logical processors (x64)
2023-09-28 21:45:10: ** GPU:              NVIDIA GeForce GTX 1060 6GB (6 GiB) (NVIDIA)
2023-09-28 21:45:10: **                   Driver: 536.23 CUDA: 11.8.89 (max supported: 12.2) Compute: 6.1
2023-09-28 21:45:10: ** System RAM:       16 GiB
2023-09-28 21:45:10: ** Target:           Windows
2023-09-28 21:45:10: ** BuildConfig:      Release
2023-09-28 21:45:10: ** Execution Env:    Native
2023-09-28 21:45:10: ** Runtime Env:      Production
2023-09-28 21:45:10: ** .NET framework:   .NET 7.0.8
2023-09-28 21:45:10: ** App DataDir:      C:\ProgramData\CodeProject\AI
2023-09-28 21:45:10: Video adapter info:
2023-09-28 21:45:10:   NVIDIA GeForce GTX 1060 6GB:
2023-09-28 21:45:10:     Driver Version     31.0.15.3623
2023-09-28 21:45:10:     Video Processor    NVIDIA GeForce GTX 1060 6GB
2023-09-28 21:45:10:   Microsoft Remote Display Adapter:
2023-09-28 21:45:10:     Driver Version     10.0.19041.2075
2023-09-28 21:45:10:     Video Processor
2023-09-28 21:45:10: *** STARTING CODEPROJECT.AI SERVER
2023-09-28 21:45:10: RUNTIMES_PATH             = C:\Program Files\CodeProject\AI\runtimes
2023-09-28 21:45:10: PREINSTALLED_MODULES_PATH = C:\Program Files\CodeProject\AI\preinstalled-modules
2023-09-28 21:45:10: MODULES_PATH              = C:\Program Files\CodeProject\AI\modules
2023-09-28 21:45:10: PYTHON_PATH               = \bin\windows\%PYTHON_RUNTIME%\venv\scripts\Python
2023-09-28 21:45:10: Data Dir                  = C:\ProgramData\CodeProject\AI
2023-09-28 21:45:10: ** Server version:   2.2.4-Beta
2023-09-28 21:45:10: ModuleRunner Start
2023-09-28 21:45:10: Starting Background AI Modules
2023-09-28 21:45:13: ** Setting up initial modules. Please be patient...
2023-09-28 21:45:13: ** Installing initial module FaceProcessing.
2023-09-28 21:45:13: Preparing to install module 'FaceProcessing'
2023-09-28 21:45:13: Downloading module 'FaceProcessing'
2023-09-28 21:45:14: Installing module 'FaceProcessing'
2023-09-28 21:45:14: Installer script at 'C:\Program Files\CodeProject\AI\setup.bat'
2023-09-28 21:45:14: FaceProcessing: [0;33m[49m             Installing CodeProject.AI Analysis Module                [0m
2023-09-28 21:45:14: FaceProcessing: [0;32m[49m========================================================================[0m
2023-09-28 21:45:14: FaceProcessing: [0;32m[49m                   CodeProject.AI Installer                             [0m
2023-09-28 21:45:14: FaceProcessing: [0;32m[49m========================================================================[0m
2023-09-28 21:45:15: FaceProcessing: [0;97m[104mChecking GPU support                                                  [0m
2023-09-28 21:45:15: FaceProcessing: [0;39m[49mCUDA Present...[0m[0;92m[49mTrue[0m
2023-09-28 21:45:15: FaceProcessing: [0;39m[49mAllowing GPU Support: [0m[0;92m[49mYes[0m
2023-09-28 21:45:15: FaceProcessing: [0;39m[49mAllowing CUDA Support: [0m[0;92m[49mYes[0m
2023-09-28 21:45:15: FaceProcessing: [0;97m[104mGeneral CodeProject.AI setup                                          [0m
2023-09-28 21:45:15: FaceProcessing: [0;39m[49mCreating Directories...[0m[0;92m[49mDone[0m
2023-09-28 21:45:15: FaceProcessing: [0;97m[104mProcessing Core SDK                                                   [0m
2023-09-28 21:45:15: FaceProcessing: [0;97m[104mInstalling module FaceProcessing 1.7                                  [0m
2023-09-28 21:45:15: Current Version is 2.2.4-Beta
2023-09-28 21:45:15: Server: This is the latest version
2023-09-28 21:45:20: FaceProcessing: Start-BitsTransfer : The resource loader cache doesn't have loaded MUI entry. (Exception from HRESULT: 0x80073B01)
2023-09-28 21:45:20: FaceProcessing: At line:1 char:1
2023-09-28 21:45:20: FaceProcessing: + Start-BitsTransfer -Source 'https://codeproject-ai.s3.ca-central-1.am ...
2023-09-28 21:45:20: FaceProcessing: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-09-28 21:45:20: FaceProcessing:     + CategoryInfo          : NotSpecified: (:) [Start-BitsTransfer], COMException
2023-09-28 21:45:20: FaceProcessing:     + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.BackgroundIntelligentTransfer.Mana 
2023-09-28 21:45:20: FaceProcessing:    gement.NewBitsTransferCommand
2023-09-28 21:45:20: FaceProcessing: [0;97m[49mDownloading Python 3.7 interpreter...[0m[0;91m[49mAn error occurred that could not be resolved.[0m
2023-09-28 21:45:20: FaceProcessing: CUDA version is 11.8
2023-09-28 21:45:20: FaceProcessing: [0;39m[49mEnsuring Python package manager (pip) is installed...[0m[0;92m[49mDone[0m
2023-09-28 21:45:20: FaceProcessing: [0;39m[49mEnsuring Python package manager (pip) is up to date...[0m[0;92m[49mDone[0m
2023-09-28 21:45:20: FaceProcessing: [0;93m[49mChoosing Python packages from requirements.windows.cuda.txt[0m
2023-09-28 21:45:20: FaceProcessing: The system cannot find the path specified.
2023-09-28 21:45:20: FaceProcessing: [0;39m[49mInstalling Packages into Virtual Environment...[0m[0;92m[49mSuccess[0m
2023-09-28 21:45:22: FaceProcessing: Start-BitsTransfer : The resource loader cache doesn't have loaded MUI entry. (Exception from HRESULT: 0x80073B01)
2023-09-28 21:45:22: FaceProcessing: At line:1 char:1
2023-09-28 21:45:22: FaceProcessing: + Start-BitsTransfer -Source 'https://codeproject-ai.s3.ca-central-1.am ...
2023-09-28 21:45:22: FaceProcessing: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-09-28 21:45:22: FaceProcessing:     + CategoryInfo          : NotSpecified: (:) [Start-BitsTransfer], COMException
2023-09-28 21:45:22: FaceProcessing:     + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.BackgroundIntelligentTransfer.Mana 
2023-09-28 21:45:22: FaceProcessing:    gement.NewBitsTransferCommand
2023-09-28 21:45:22: FaceProcessing: [0;97m[49mDownloading YOLO models...[0m[0;91m[49mAn error occurred that could not be resolved.[0m
2023-09-28 21:45:22: FaceProcessing: [0;39m[49mInstalling Server SDK support:[0m
2023-09-28 21:45:22: FaceProcessing: CUDA version is 11.8
2023-09-28 21:45:22: FaceProcessing: [0;39m[49mEnsuring Python package manager (pip) is installed...[0m[0;92m[49mDone[0m
2023-09-28 21:45:22: FaceProcessing: [0;39m[49mEnsuring Python package manager (pip) is up to date...[0m[0;92m[49mDone[0m
2023-09-28 21:45:22: FaceProcessing: [0;93m[49mChoosing Python packages from requirements.txt[0m
2023-09-28 21:45:22: FaceProcessing: The system cannot find the path specified.
2023-09-28 21:45:22: FaceProcessing: [0;39m[49mInstalling Packages into Virtual Environment...[0m[0;92m[49mSuccess[0m
2023-09-28 21:45:22: FaceProcessing: [0;97m[42mSetup complete                                                        [0m
2023-09-28 21:45:22: Module FaceProcessing installed successfully.
2023-09-28 21:45:22: GetCommandByRuntime: Runtime=python37, Location=Shared
2023-09-28 21:45:22: Command: C:\Program Files\CodeProject\AI\runtimes\bin\windows\python37\venv\scripts\Python
2023-09-28 21:45:22: 
2023-09-28 21:45:22: Attempting to start FaceProcessing with C:\Program Files\CodeProject\AI\runtimes\bin\windows\python37\venv\scripts\Python "C:\Program Files\CodeProject\AI\modules\FaceProcessing\intelligencelayer\face.py"
2023-09-28 21:45:22: Starting C:\Program Files...ws\python37\venv\scripts\Python "C:\Program Files...ing\intelligencelayer\face.py"
2023-09-28 21:45:22: 
2023-09-28 21:45:22: ** Module 'Face Processing' 1.7 (ID: FaceProcessing)
2023-09-28 21:45:22: ** Module Path:   C:\Program Files\CodeProject\AI\modules\FaceProcessing
2023-09-28 21:45:22: ** AutoStart:     True
2023-09-28 21:45:22: ** Queue:         faceprocessing_queue
2023-09-28 21:45:22: ** Platforms:     windows,linux,linux-arm64,macos,macos-arm64
2023-09-28 21:45:22: ** GPU:           Support enabled
2023-09-28 21:45:22: ** Parallelism:   0
2023-09-28 21:45:22: ** Accelerator:
2023-09-28 21:45:22: ** Half Precis.:  enable
2023-09-28 21:45:22: ** Runtime:       python37
2023-09-28 21:45:22: ** Runtime Loc:   Shared
2023-09-28 21:45:22: ** FilePath:      intelligencelayer\face.py
2023-09-28 21:45:22: ** Pre installed: False
2023-09-28 21:45:22: ** Start pause:   3 sec
2023-09-28 21:45:22: ** LogVerbosity:
2023-09-28 21:45:22: ** Valid:         True
2023-09-28 21:45:22: ** Environment Variables
2023-09-28 21:45:22: ** APPDIR             = %CURRENT_MODULE_PATH%\intelligencelayer
2023-09-28 21:45:22: ** DATA_DIR           = %DATA_DIR%
2023-09-28 21:45:22: ** MODE               = MEDIUM
2023-09-28 21:45:22: ** MODELS_DIR         = %CURRENT_MODULE_PATH%\assets
2023-09-28 21:45:22: ** PROFILE            = desktop_gpu
2023-09-28 21:45:22: ** USE_CUDA           = True
2023-09-28 21:45:22: ** YOLOv5_AUTOINSTALL = false
2023-09-28 21:45:22: ** YOLOv5_VERBOSE     = false
2023-09-28 21:45:22: 
2023-09-28 21:45:22 [System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Program Files\CodeProject\AI\runtimes\bin\windows\python37\venv\scripts\Python' with working directory 'C:\Program Files\CodeProject\AI\modules\FaceProcessing'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at CodeProject.AI.Server.Modules.ModuleProcessServices.StartProcess(ModuleConfig module)]: Error trying to start Face Processing (intelligencelayer\face.py)
2023-09-28 21:45:22: An error occurred trying to start process 'C:\Program Files\CodeProject\AI\runtimes\bin\windows\python37\venv\scripts\Python' with working directory 'C:\Program Files\CodeProject\AI\modules\FaceProcessing'. The system cannot find the file specified.
2023-09-28 21:45:22:    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at CodeProject.AI.Server.Modules.ModuleProcessServices.StartProcess(ModuleConfig module)
2023-09-28 21:45:22: *** Please check the CodeProject.AI installation completed successfully
2023-09-28 21:45:22: Module FaceProcessing started successfully.
2023-09-28 21:45:22: Installer exited with code 1
2023-09-28 21:45:22: ** Installing initial module ObjectDetectionNet.
2023-09-28 21:45:22: Preparing to install module 'ObjectDetectionNet'
2023-09-28 21:45:22: Downloading module 'ObjectDetectionNet'
2023-09-28 21:45:23: Installing module 'ObjectDetectionNet'
2023-09-28 21:45:23: Installer script at 'C:\Program Files\CodeProject\AI\setup.bat'
```

**Comment by RGN01** [comment]
I have the same issue - new clean Win 10 install (OS reset), BI and CPAI installed onto refreshed OS. I'm very much a beginner and out of my depth with Python but happy to try to help diagnose and test.

**Comment by ChrisMaunder** [comment]
This should now be fixed
