### ISSUE TITLE
License Plate Reader 2.7.2 fails to start

### ISSUE THREAD

**Issue by symb10z** [codeproject/CodeProject.AI-Server#79]
**Area of Concern**
- [ ] Server
- [x] Behaviour of one or more Modules [Plate Reader 2.7.2]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**
License Plate Reader 2.7.2 fails to start

**Expected behavior**
License Plate Reader 2.7.2 should start

**Screenshots**
Here is error log:
```shell
12:59:44:
12:59:44:Started License Plate Reader module
12:59:44:ALPR_adapter.py: Traceback (most recent call last):
12:59:44:ALPR_adapter.py:   File "/app/modules/ALPR/ALPR_adapter.py", line 8, in 
12:59:44:ALPR_adapter.py:     from module_runner import ModuleRunner
12:59:44:ALPR_adapter.py:   File "/app/modules/ALPR/../../SDK/Python/module_runner.py", line 33, in 
12:59:44:ALPR_adapter.py:     import aiohttp
12:59:44:ALPR_adapter.py: ModuleNotFoundError: No module named 'aiohttp'
12:59:44:Module ALPR has shutdown
12:59:45:
``` 
I've checked ALPR module's requirements, and didn't found aiohttp.

**Your System (please complete the following information):**

Docker image: codeproject/**ai-server:latest**
```shell
Server version:   2.3.2-Alpha
System:           Docker
Operating System: Linux (Linux 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023)
CPUs:             12th Gen Intel(R) Core(TM) i5-12500H (Intel)
                  1 CPU x 8 cores. 16 logical processors (x64)
GPU:              NVIDIA GeForce RTX 3050 Laptop GPU (4 GiB) (NVIDIA) 
                  Driver: 546.17 CUDA: 11.5.119 (max supported: 12.3) Compute: 8.6
System RAM:       31 GiB
Target:           Linux
BuildConfig:      Release
Execution Env:    Docker
Runtime Env:      Production
.NET framework:   .NET 7.0.13
Video adapter info:
System GPU info:
  GPU 3D Usage       7%
  GPU RAM Usage      494 MiB
Global Environment variables:
  CPAI_APPROOTPATH = <root>
  CPAI_PORT        = 32168
``` 

**Additional context**

Same error with docker images:
codeproject/ai-server:cuda12_2
codeproject/ai-server:cuda11_7

**Comment by SeanECP** [comment]
Is this still happening for newer images? Like 2.5.6

**Comment by onlineapps-cloud** [comment]
> Is this still happening for newer images? Like 2.5.6

yes, same problem persist in v 2.6.2
